// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.15.6
// source: content_svr/protobuf/pbmgdb/mg_db.proto

package pbmgdb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecretWorksLikeRecordMgDbModel
type IpAddressMgDbModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	// @inject_tag: bson:"province"
	Province *string `protobuf:"bytes,2,opt,name=province,proto3,oneof" json:"province,omitempty" bson:"province"`
	// @inject_tag: bson:"city"
	City *string `protobuf:"bytes,3,opt,name=city,proto3,oneof" json:"city,omitempty" bson:"city"`
	// @inject_tag: bson:"longitude"
	Longitude *float64 `protobuf:"fixed64,4,opt,name=longitude,proto3,oneof" json:"longitude,omitempty" bson:"longitude"`
	// @inject_tag: bson:"latitude"
	Latitude *float64 `protobuf:"fixed64,5,opt,name=latitude,proto3,oneof" json:"latitude,omitempty" bson:"latitude"`
	// @inject_tag: bson:"cityCode"
	CityCode *int32 `protobuf:"varint,6,opt,name=cityCode,proto3,oneof" json:"cityCode,omitempty" bson:"cityCode"`
}

func (x *IpAddressMgDbModel) Reset() {
	*x = IpAddressMgDbModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_content_svr_protobuf_pbmgdb_mg_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpAddressMgDbModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpAddressMgDbModel) ProtoMessage() {}

func (x *IpAddressMgDbModel) ProtoReflect() protoreflect.Message {
	mi := &file_content_svr_protobuf_pbmgdb_mg_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpAddressMgDbModel.ProtoReflect.Descriptor instead.
func (*IpAddressMgDbModel) Descriptor() ([]byte, []int) {
	return file_content_svr_protobuf_pbmgdb_mg_db_proto_rawDescGZIP(), []int{0}
}

func (x *IpAddressMgDbModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IpAddressMgDbModel) GetProvince() string {
	if x != nil && x.Province != nil {
		return *x.Province
	}
	return ""
}

func (x *IpAddressMgDbModel) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *IpAddressMgDbModel) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *IpAddressMgDbModel) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *IpAddressMgDbModel) GetCityCode() int32 {
	if x != nil && x.CityCode != nil {
		return *x.CityCode
	}
	return 0
}

var File_content_svr_protobuf_pbmgdb_mg_db_proto protoreflect.FileDescriptor

var file_content_svr_protobuf_pbmgdb_mg_db_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x76, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x62, 0x6d, 0x67, 0x64, 0x62, 0x2f, 0x6d, 0x67,
	0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x02, 0x0a, 0x12, 0x69, 0x70,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4d, 0x67, 0x44, 0x62, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x17, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x6c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x48,
	0x03, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f,
	0x0a, 0x08, 0x63, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x04, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x42,
	0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x63, 0x69, 0x74, 0x79, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x24, 0x5a,
	0x22, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x76, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x62, 0x6d, 0x67, 0x64, 0x62, 0x3b, 0x70, 0x62, 0x6d,
	0x67, 0x64, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_content_svr_protobuf_pbmgdb_mg_db_proto_rawDescOnce sync.Once
	file_content_svr_protobuf_pbmgdb_mg_db_proto_rawDescData = file_content_svr_protobuf_pbmgdb_mg_db_proto_rawDesc
)

func file_content_svr_protobuf_pbmgdb_mg_db_proto_rawDescGZIP() []byte {
	file_content_svr_protobuf_pbmgdb_mg_db_proto_rawDescOnce.Do(func() {
		file_content_svr_protobuf_pbmgdb_mg_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_content_svr_protobuf_pbmgdb_mg_db_proto_rawDescData)
	})
	return file_content_svr_protobuf_pbmgdb_mg_db_proto_rawDescData
}

var file_content_svr_protobuf_pbmgdb_mg_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_content_svr_protobuf_pbmgdb_mg_db_proto_goTypes = []interface{}{
	(*IpAddressMgDbModel)(nil), // 0: ipAddressMgDbModel
}
var file_content_svr_protobuf_pbmgdb_mg_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_content_svr_protobuf_pbmgdb_mg_db_proto_init() }
func file_content_svr_protobuf_pbmgdb_mg_db_proto_init() {
	if File_content_svr_protobuf_pbmgdb_mg_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_content_svr_protobuf_pbmgdb_mg_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpAddressMgDbModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_content_svr_protobuf_pbmgdb_mg_db_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_content_svr_protobuf_pbmgdb_mg_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_content_svr_protobuf_pbmgdb_mg_db_proto_goTypes,
		DependencyIndexes: file_content_svr_protobuf_pbmgdb_mg_db_proto_depIdxs,
		MessageInfos:      file_content_svr_protobuf_pbmgdb_mg_db_proto_msgTypes,
	}.Build()
	File_content_svr_protobuf_pbmgdb_mg_db_proto = out.File
	file_content_svr_protobuf_pbmgdb_mg_db_proto_rawDesc = nil
	file_content_svr_protobuf_pbmgdb_mg_db_proto_goTypes = nil
	file_content_svr_protobuf_pbmgdb_mg_db_proto_depIdxs = nil
}
